### ISSUE TITLE
Translate readme to English

### ISSUE THREAD

**Issue by mathcale** [mathcale/react-native-buscacnpj#1]
This project is targeted to brazilians, however it could be useful to show this skill to international recruiters

**Comment by Jpfonseca** [comment]
It would help if you had all the sentences on a xml or a Json file. It would look cleaner too.

**Comment by mdelclaro** [comment]
Criei um Pull Request. Dá uma olhada e vê se tá ok! :)

**Comment by mathcale** [comment]
Close #6
